### ISSUE TITLE
Naming conflict — there's another Rust-based `cw`

### ISSUE THREAD

**Issue by ahfornitani** [Altair-Bueno/cw#32]
Hi! First of all, thanks for your tool!

I've been testing Rust alternatives to coreutils just for fun, and I thought I'd try an alternative to `wc`. 
But having searched for "alternative to wc rust", I have found both yours and this other tool with the same name: <https://github.com/Freaky/cw>

Given that your tool is newer (and more up-to-date), maybe it would be a good idea to change its name, to differentiate it?

**Comment by ahfornitani** [comment]
Hm, I can't say I'm good at naming things either, but some suggestions:
- **wcr** for "word countr" (like those vowel-dropping site names, e.g. "flickr" and "tumblr")
    - this one also looks like "**wc** [for] **R**ust"
    - But it also has a naming conflict (I checked after having typed the whole comment…: https://github.com/mehdi-farsi/wcr )

- The second suggestion would be "**wz**", a literal translation into German ("word count" → "Wortzahl")
    - this one keeps the two-lettered keystroke
    - Con: Naming conflict - https://github.com/truemedian/wz (apparently "z" is used for new Zig projects the same way as some people use "r" for Rust)

- Use "oxide" , e.g. "wcoxide" 
    - like there's the Rust version of "z - jump around" named "[zoxide](https://github.com/ajeetdsouza/zoxide)"
    
- You could merge the above suggestions, e.g. "wzr", "wcwz", "cwwz", "cwwc" (but not "rwc" as that one [is taken](https://github.com/steveklabnik/rwc)) for the repo name, but keep the executable shorter. Or just name the repo with an actual word (Conteo, Recuento, Wortzahl, Wortzähler etc) and do whatever with the executable (there's always the option to use aliases, in case someone doesn't like the name of a program).

- Finally, there's in Spanish "cantaor" from "[cantador](https://dle.rae.es/cantador)", isn't there? 
    - So perhaps you could name it "contaoR" from "[contador](https://dle.rae.es/contador)"? (the capital "R" from "Rust")
    
Hope one of these is useful. If not, at least they might spur some other ideas :)

**Comment by Altair-Bueno** [comment]
Thanks for your suggestions! I do really like `wz` and I don't think using the same name is an issue here. They solve different problems and they do not share the same functionality at all. Plus, https://crates.io doesn't have any crate called `wz`. Nonetheless, I'm a bit sceptical about having the letter `z` on the name: it is not as ergonomic to type as other letters on a qwerty keyboard (which is probably what most people use)

![](https://user-images.githubusercontent.com/67512202/168440660-cbaca819-580c-4afa-93ce-6a81289c3c65.png)

> Z uses your pinky finger

For now, I'm keeping this issue open and pinned. I'm open to more suggestions from anyone interested on this project. 

---

> (there's always the option to use aliases, in case someone doesn't like the name of a program).

Although this is true, my goal is to make a better overall `wc` tool. This includes things like coloured output, structured output, convenience and sensible defaults. The user shouldn't be responsible of choosing a new alias for their UNIX word counter

**Comment by Altair-Bueno** [comment]
Due to limitations on `cw`'s original design I've decided to refactor the codebase and create a new crate. It's called [wz](https://github.com/Altair-Bueno/wz) (thanks for the suggestion) and It's licensed under the same MIT license as `cw`

### What happens with `cw`?

`cw` is now **deprecated**. I have no plans on adding features nor release bug fixes

### X feature is missing on `wz`, but available on `cw`

Open a new issue on `wz` or submit a pull request. I'm currently working on bringing feature parity to `wz`.
